// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Article struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Content        string     `json:"content"`
	Summary        *string    `json:"summary"`
	SourceType     *string    `json:"source_type"`
	SourceUrl      *string    `json:"source_url"`
	Author         *string    `json:"author"`
	PublishedAt    *time.Time `json:"published_at"`
	Language       *string    `json:"language"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	Status         *string    `json:"status"`
	SourceID       *string    `json:"source_id"`
	ParentID       *string    `json:"parent_id"`
	Sections       *string    `json:"sections"`
	CustomMetadata *string    `json:"custom_metadata"`
}

type ArticleRelation struct {
	FromArticleID *string   `json:"from_article_id"`
	ToArticleID   *string   `json:"to_article_id"`
	RelationType  *string   `json:"relation_type"`
	Metadata      *string   `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

type ArticleTag struct {
	ArticleID *string `json:"article_id"`
	TagID     *int64  `json:"tag_id"`
}

type ArticlesFt struct {
	ArticleID string `json:"article_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Summary   string `json:"summary"`
}

type ProcessingArtifact struct {
	ID        string    `json:"id"`
	SourceID  *string   `json:"source_id"`
	Type      string    `json:"type"`
	Content   *string   `json:"content"`
	Format    *string   `json:"format"`
	FilePath  *string   `json:"file_path"`
	Metadata  *string   `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type ProcessingJob struct {
	ID          string     `json:"id"`
	SourceID    *string    `json:"source_id"`
	Type        string     `json:"type"`
	Status      *string    `json:"status"`
	Priority    *int64     `json:"priority"`
	Progress    *int64     `json:"progress"`
	RetryCount  *int64     `json:"retry_count"`
	Error       *string    `json:"error"`
	CreatedAt   time.Time  `json:"created_at"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
}

type Source struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"`
	OriginalUrl *string   `json:"original_url"`
	FilePath    *string   `json:"file_path"`
	Metadata    *string   `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	Status      *string   `json:"status"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Color     *string   `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}
