// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package sqlc

import (
	"context"
	"time"
)

const createArtifact = `-- name: CreateArtifact :exec
INSERT INTO processing_artifacts (id, source_id, type, content, format, file_path, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateArtifactParams struct {
	ID        string    `json:"id"`
	SourceID  *string   `json:"source_id"`
	Type      string    `json:"type"`
	Content   *string   `json:"content"`
	Format    *string   `json:"format"`
	FilePath  *string   `json:"file_path"`
	Metadata  *string   `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) error {
	_, err := q.db.ExecContext(ctx, createArtifact,
		arg.ID,
		arg.SourceID,
		arg.Type,
		arg.Content,
		arg.Format,
		arg.FilePath,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const createSource = `-- name: CreateSource :exec
INSERT INTO sources (id, type, original_url, file_path, metadata, created_at, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSourceParams struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"`
	OriginalUrl *string   `json:"original_url"`
	FilePath    *string   `json:"file_path"`
	Metadata    *string   `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	Status      *string   `json:"status"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) error {
	_, err := q.db.ExecContext(ctx, createSource,
		arg.ID,
		arg.Type,
		arg.OriginalUrl,
		arg.FilePath,
		arg.Metadata,
		arg.CreatedAt,
		arg.Status,
	)
	return err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM processing_artifacts WHERE id = ?
`

func (q *Queries) DeleteArtifact(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const deleteArtifactsBySourceID = `-- name: DeleteArtifactsBySourceID :exec
DELETE FROM processing_artifacts WHERE source_id = ?
`

func (q *Queries) DeleteArtifactsBySourceID(ctx context.Context, sourceID *string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifactsBySourceID, sourceID)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, source_id, type, content, format, file_path, metadata, created_at
FROM processing_artifacts WHERE id = ?
`

func (q *Queries) GetArtifactByID(ctx context.Context, id string) (ProcessingArtifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByID, id)
	var i ProcessingArtifact
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Type,
		&i.Content,
		&i.Format,
		&i.FilePath,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactsBySourceID = `-- name: GetArtifactsBySourceID :many
SELECT id, source_id, type, content, format, file_path, metadata, created_at
FROM processing_artifacts
WHERE source_id = ?
ORDER BY created_at
`

func (q *Queries) GetArtifactsBySourceID(ctx context.Context, sourceID *string) ([]ProcessingArtifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsBySourceID, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessingArtifact{}
	for rows.Next() {
		var i ProcessingArtifact
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Type,
			&i.Content,
			&i.Format,
			&i.FilePath,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, type, original_url, file_path, metadata, created_at, status
FROM sources WHERE id = ?
`

func (q *Queries) GetSourceByID(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OriginalUrl,
		&i.FilePath,
		&i.Metadata,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, type, original_url, file_path, metadata, created_at, status
FROM sources
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSourcesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OriginalUrl,
			&i.FilePath,
			&i.Metadata,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceStatus = `-- name: UpdateSourceStatus :exec
UPDATE sources SET status = ? WHERE id = ?
`

type UpdateSourceStatusParams struct {
	Status *string `json:"status"`
	ID     string  `json:"id"`
}

func (q *Queries) UpdateSourceStatus(ctx context.Context, arg UpdateSourceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceStatus, arg.Status, arg.ID)
	return err
}
