// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"time"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, color, created_at)
VALUES (?, ?, ?)
RETURNING id, name, color, created_at
`

type CreateTagParams struct {
	Name      string    `json:"name"`
	Color     *string   `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Color, arg.CreatedAt)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleTagsByTagID = `-- name: DeleteArticleTagsByTagID :exec
DELETE FROM article_tags WHERE tag_id = ?
`

func (q *Queries) DeleteArticleTagsByTagID(ctx context.Context, tagID *int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleTagsByTagID, tagID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, color, created_at FROM tags WHERE id = ?
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, color, created_at FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, created_at FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCount = `-- name: ListTagsWithCount :many
SELECT t.id, t.name, t.color, t.created_at, COUNT(at.article_id) as count
FROM tags t
LEFT JOIN article_tags at ON t.id = at.tag_id
GROUP BY t.id
ORDER BY count DESC, t.name
`

type ListTagsWithCountRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Color     *string   `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	Count     int64     `json:"count"`
}

func (q *Queries) ListTagsWithCount(ctx context.Context) ([]ListTagsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithCountRow{}
	for rows.Next() {
		var i ListTagsWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags SET name = ?, color = ? WHERE id = ?
`

type UpdateTagParams struct {
	Name  string  `json:"name"`
	Color *string `json:"color"`
	ID    int64   `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	return err
}
